### ISSUE TITLE
Has this repo already finished yet?

### ISSUE THREAD

**Issue by Ichliebedich0505** [kkeian/epub-to-txt#1]
I get nothing output after i ran it

**Comment by kkeian** [comment]
Right now I don't have time to write a custom XML parser.
When I was working on this last month I couldn't see a straightforward/obvious way I could see to make the `encoding/xml` module parse my test Epub files correctly.

The Epub files I have use some HTML tags that the XML parser doesn't support. I left the project up in case anyone wants to build on the little I created so far.

If you take a look at the `main.go` file there isn't yet logic for parsing the XML file. The `parser.go` file has the beginnings of a parser (as I've imagined it) with the `findTagIndices` func.

Feel free to add to the project. Fork it and put in a MR.

**Comment by Ichliebedich0505** [comment]
> Right now I don't have time to write a custom XML parser. When I was working on this last month I couldn't see a straightforward/obvious way I could see to make the `encoding/xml` module parse my test Epub files correctly.
> 
> The Epub files I have use some HTML tags that the XML parser doesn't support. I left the project up in case anyone wants to build on the little I created so far.
> 
> If you take a look at the `main.go` file there isn't yet logic for parsing the XML file. The `parser.go` file has the beginnings of a parser (as I've imagined it) with the `findTagIndices` func.
> 
> Feel free to add to the project. Fork it and put in a MR.

Okay I get it
